// Code generated by go-swagger; DO NOT EDIT.

package champion_mastery

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetChampionMasteryHandlerFunc turns a function with the right signature into a get champion mastery handler
type GetChampionMasteryHandlerFunc func(GetChampionMasteryParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetChampionMasteryHandlerFunc) Handle(params GetChampionMasteryParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetChampionMasteryHandler interface for that can handle valid get champion mastery params
type GetChampionMasteryHandler interface {
	Handle(GetChampionMasteryParams, interface{}) middleware.Responder
}

// NewGetChampionMastery creates a new http.Handler for the get champion mastery operation
func NewGetChampionMastery(ctx *middleware.Context, handler GetChampionMasteryHandler) *GetChampionMastery {
	return &GetChampionMastery{Context: ctx, Handler: handler}
}

/*GetChampionMastery swagger:route GET /champion-mastery/v4/champion-masteries/by-summoner/{encryptedSummonerId}/by-champion/{championId} championMastery getChampionMastery

Get a champion mastery by player ID and champion ID

*/
type GetChampionMastery struct {
	Context *middleware.Context
	Handler GetChampionMasteryHandler
}

func (o *GetChampionMastery) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetChampionMasteryParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
