// Code generated by go-swagger; DO NOT EDIT.

package champion_mastery

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAllChampionMasteriesParams creates a new GetAllChampionMasteriesParams object
// no default values defined in spec.
func NewGetAllChampionMasteriesParams() GetAllChampionMasteriesParams {

	return GetAllChampionMasteriesParams{}
}

// GetAllChampionMasteriesParams contains all the bound params for the get all champion masteries operation
// typically these are obtained from a http.Request
//
// swagger:parameters getAllChampionMasteries
type GetAllChampionMasteriesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Summoner ID associated with the player
	  Required: true
	  In: path
	*/
	EncryptedSummonerID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetAllChampionMasteriesParams() beforehand.
func (o *GetAllChampionMasteriesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rEncryptedSummonerID, rhkEncryptedSummonerID, _ := route.Params.GetOK("encryptedSummonerId")
	if err := o.bindEncryptedSummonerID(rEncryptedSummonerID, rhkEncryptedSummonerID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindEncryptedSummonerID binds and validates parameter EncryptedSummonerID from path.
func (o *GetAllChampionMasteriesParams) bindEncryptedSummonerID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.EncryptedSummonerID = raw

	return nil
}
