// Code generated by go-swagger; DO NOT EDIT.

package champion_mastery

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/andresperezl/gol/models"
)

// GetAllChampionMasteriesOKCode is the HTTP code returned for type GetAllChampionMasteriesOK
const GetAllChampionMasteriesOKCode int = 200

/*GetAllChampionMasteriesOK OK

swagger:response getAllChampionMasteriesOK
*/
type GetAllChampionMasteriesOK struct {

	/*
	  In: Body
	*/
	Payload models.ListChampionMastery `json:"body,omitempty"`
}

// NewGetAllChampionMasteriesOK creates GetAllChampionMasteriesOK with default headers values
func NewGetAllChampionMasteriesOK() *GetAllChampionMasteriesOK {

	return &GetAllChampionMasteriesOK{}
}

// WithPayload adds the payload to the get all champion masteries o k response
func (o *GetAllChampionMasteriesOK) WithPayload(payload models.ListChampionMastery) *GetAllChampionMasteriesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all champion masteries o k response
func (o *GetAllChampionMasteriesOK) SetPayload(payload models.ListChampionMastery) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllChampionMasteriesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.ListChampionMastery{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetAllChampionMasteriesBadRequestCode is the HTTP code returned for type GetAllChampionMasteriesBadRequest
const GetAllChampionMasteriesBadRequestCode int = 400

/*GetAllChampionMasteriesBadRequest Bad request

swagger:response getAllChampionMasteriesBadRequest
*/
type GetAllChampionMasteriesBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAllChampionMasteriesBadRequest creates GetAllChampionMasteriesBadRequest with default headers values
func NewGetAllChampionMasteriesBadRequest() *GetAllChampionMasteriesBadRequest {

	return &GetAllChampionMasteriesBadRequest{}
}

// WithPayload adds the payload to the get all champion masteries bad request response
func (o *GetAllChampionMasteriesBadRequest) WithPayload(payload *models.Error) *GetAllChampionMasteriesBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all champion masteries bad request response
func (o *GetAllChampionMasteriesBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllChampionMasteriesBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAllChampionMasteriesUnauthorizedCode is the HTTP code returned for type GetAllChampionMasteriesUnauthorized
const GetAllChampionMasteriesUnauthorizedCode int = 401

/*GetAllChampionMasteriesUnauthorized Unauthorized

swagger:response getAllChampionMasteriesUnauthorized
*/
type GetAllChampionMasteriesUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAllChampionMasteriesUnauthorized creates GetAllChampionMasteriesUnauthorized with default headers values
func NewGetAllChampionMasteriesUnauthorized() *GetAllChampionMasteriesUnauthorized {

	return &GetAllChampionMasteriesUnauthorized{}
}

// WithPayload adds the payload to the get all champion masteries unauthorized response
func (o *GetAllChampionMasteriesUnauthorized) WithPayload(payload *models.Error) *GetAllChampionMasteriesUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all champion masteries unauthorized response
func (o *GetAllChampionMasteriesUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllChampionMasteriesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAllChampionMasteriesForbiddenCode is the HTTP code returned for type GetAllChampionMasteriesForbidden
const GetAllChampionMasteriesForbiddenCode int = 403

/*GetAllChampionMasteriesForbidden Forbidden

swagger:response getAllChampionMasteriesForbidden
*/
type GetAllChampionMasteriesForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAllChampionMasteriesForbidden creates GetAllChampionMasteriesForbidden with default headers values
func NewGetAllChampionMasteriesForbidden() *GetAllChampionMasteriesForbidden {

	return &GetAllChampionMasteriesForbidden{}
}

// WithPayload adds the payload to the get all champion masteries forbidden response
func (o *GetAllChampionMasteriesForbidden) WithPayload(payload *models.Error) *GetAllChampionMasteriesForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all champion masteries forbidden response
func (o *GetAllChampionMasteriesForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllChampionMasteriesForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAllChampionMasteriesNotFoundCode is the HTTP code returned for type GetAllChampionMasteriesNotFound
const GetAllChampionMasteriesNotFoundCode int = 404

/*GetAllChampionMasteriesNotFound Not found

swagger:response getAllChampionMasteriesNotFound
*/
type GetAllChampionMasteriesNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAllChampionMasteriesNotFound creates GetAllChampionMasteriesNotFound with default headers values
func NewGetAllChampionMasteriesNotFound() *GetAllChampionMasteriesNotFound {

	return &GetAllChampionMasteriesNotFound{}
}

// WithPayload adds the payload to the get all champion masteries not found response
func (o *GetAllChampionMasteriesNotFound) WithPayload(payload *models.Error) *GetAllChampionMasteriesNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all champion masteries not found response
func (o *GetAllChampionMasteriesNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllChampionMasteriesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAllChampionMasteriesMethodNotAllowedCode is the HTTP code returned for type GetAllChampionMasteriesMethodNotAllowed
const GetAllChampionMasteriesMethodNotAllowedCode int = 405

/*GetAllChampionMasteriesMethodNotAllowed Method not allowed

swagger:response getAllChampionMasteriesMethodNotAllowed
*/
type GetAllChampionMasteriesMethodNotAllowed struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAllChampionMasteriesMethodNotAllowed creates GetAllChampionMasteriesMethodNotAllowed with default headers values
func NewGetAllChampionMasteriesMethodNotAllowed() *GetAllChampionMasteriesMethodNotAllowed {

	return &GetAllChampionMasteriesMethodNotAllowed{}
}

// WithPayload adds the payload to the get all champion masteries method not allowed response
func (o *GetAllChampionMasteriesMethodNotAllowed) WithPayload(payload *models.Error) *GetAllChampionMasteriesMethodNotAllowed {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all champion masteries method not allowed response
func (o *GetAllChampionMasteriesMethodNotAllowed) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllChampionMasteriesMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAllChampionMasteriesUnsupportedMediaTypeCode is the HTTP code returned for type GetAllChampionMasteriesUnsupportedMediaType
const GetAllChampionMasteriesUnsupportedMediaTypeCode int = 415

/*GetAllChampionMasteriesUnsupportedMediaType Unsopported media type

swagger:response getAllChampionMasteriesUnsupportedMediaType
*/
type GetAllChampionMasteriesUnsupportedMediaType struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAllChampionMasteriesUnsupportedMediaType creates GetAllChampionMasteriesUnsupportedMediaType with default headers values
func NewGetAllChampionMasteriesUnsupportedMediaType() *GetAllChampionMasteriesUnsupportedMediaType {

	return &GetAllChampionMasteriesUnsupportedMediaType{}
}

// WithPayload adds the payload to the get all champion masteries unsupported media type response
func (o *GetAllChampionMasteriesUnsupportedMediaType) WithPayload(payload *models.Error) *GetAllChampionMasteriesUnsupportedMediaType {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all champion masteries unsupported media type response
func (o *GetAllChampionMasteriesUnsupportedMediaType) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllChampionMasteriesUnsupportedMediaType) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(415)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAllChampionMasteriesTooManyRequestsCode is the HTTP code returned for type GetAllChampionMasteriesTooManyRequests
const GetAllChampionMasteriesTooManyRequestsCode int = 429

/*GetAllChampionMasteriesTooManyRequests Rate limit Exceeded

swagger:response getAllChampionMasteriesTooManyRequests
*/
type GetAllChampionMasteriesTooManyRequests struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAllChampionMasteriesTooManyRequests creates GetAllChampionMasteriesTooManyRequests with default headers values
func NewGetAllChampionMasteriesTooManyRequests() *GetAllChampionMasteriesTooManyRequests {

	return &GetAllChampionMasteriesTooManyRequests{}
}

// WithPayload adds the payload to the get all champion masteries too many requests response
func (o *GetAllChampionMasteriesTooManyRequests) WithPayload(payload *models.Error) *GetAllChampionMasteriesTooManyRequests {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all champion masteries too many requests response
func (o *GetAllChampionMasteriesTooManyRequests) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllChampionMasteriesTooManyRequests) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(429)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAllChampionMasteriesInternalServerErrorCode is the HTTP code returned for type GetAllChampionMasteriesInternalServerError
const GetAllChampionMasteriesInternalServerErrorCode int = 500

/*GetAllChampionMasteriesInternalServerError Internal server error

swagger:response getAllChampionMasteriesInternalServerError
*/
type GetAllChampionMasteriesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAllChampionMasteriesInternalServerError creates GetAllChampionMasteriesInternalServerError with default headers values
func NewGetAllChampionMasteriesInternalServerError() *GetAllChampionMasteriesInternalServerError {

	return &GetAllChampionMasteriesInternalServerError{}
}

// WithPayload adds the payload to the get all champion masteries internal server error response
func (o *GetAllChampionMasteriesInternalServerError) WithPayload(payload *models.Error) *GetAllChampionMasteriesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all champion masteries internal server error response
func (o *GetAllChampionMasteriesInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllChampionMasteriesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAllChampionMasteriesBadGatewayCode is the HTTP code returned for type GetAllChampionMasteriesBadGateway
const GetAllChampionMasteriesBadGatewayCode int = 502

/*GetAllChampionMasteriesBadGateway Bad gateway

swagger:response getAllChampionMasteriesBadGateway
*/
type GetAllChampionMasteriesBadGateway struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAllChampionMasteriesBadGateway creates GetAllChampionMasteriesBadGateway with default headers values
func NewGetAllChampionMasteriesBadGateway() *GetAllChampionMasteriesBadGateway {

	return &GetAllChampionMasteriesBadGateway{}
}

// WithPayload adds the payload to the get all champion masteries bad gateway response
func (o *GetAllChampionMasteriesBadGateway) WithPayload(payload *models.Error) *GetAllChampionMasteriesBadGateway {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all champion masteries bad gateway response
func (o *GetAllChampionMasteriesBadGateway) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllChampionMasteriesBadGateway) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(502)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAllChampionMasteriesServiceUnavailableCode is the HTTP code returned for type GetAllChampionMasteriesServiceUnavailable
const GetAllChampionMasteriesServiceUnavailableCode int = 503

/*GetAllChampionMasteriesServiceUnavailable Service Unavailable

swagger:response getAllChampionMasteriesServiceUnavailable
*/
type GetAllChampionMasteriesServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAllChampionMasteriesServiceUnavailable creates GetAllChampionMasteriesServiceUnavailable with default headers values
func NewGetAllChampionMasteriesServiceUnavailable() *GetAllChampionMasteriesServiceUnavailable {

	return &GetAllChampionMasteriesServiceUnavailable{}
}

// WithPayload adds the payload to the get all champion masteries service unavailable response
func (o *GetAllChampionMasteriesServiceUnavailable) WithPayload(payload *models.Error) *GetAllChampionMasteriesServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all champion masteries service unavailable response
func (o *GetAllChampionMasteriesServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllChampionMasteriesServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAllChampionMasteriesGatewayTimeoutCode is the HTTP code returned for type GetAllChampionMasteriesGatewayTimeout
const GetAllChampionMasteriesGatewayTimeoutCode int = 504

/*GetAllChampionMasteriesGatewayTimeout Gateway timeout

swagger:response getAllChampionMasteriesGatewayTimeout
*/
type GetAllChampionMasteriesGatewayTimeout struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAllChampionMasteriesGatewayTimeout creates GetAllChampionMasteriesGatewayTimeout with default headers values
func NewGetAllChampionMasteriesGatewayTimeout() *GetAllChampionMasteriesGatewayTimeout {

	return &GetAllChampionMasteriesGatewayTimeout{}
}

// WithPayload adds the payload to the get all champion masteries gateway timeout response
func (o *GetAllChampionMasteriesGatewayTimeout) WithPayload(payload *models.Error) *GetAllChampionMasteriesGatewayTimeout {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all champion masteries gateway timeout response
func (o *GetAllChampionMasteriesGatewayTimeout) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllChampionMasteriesGatewayTimeout) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(504)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
