// Code generated by go-swagger; DO NOT EDIT.

package champion_mastery

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAllChampionMasteriesHandlerFunc turns a function with the right signature into a get all champion masteries handler
type GetAllChampionMasteriesHandlerFunc func(GetAllChampionMasteriesParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAllChampionMasteriesHandlerFunc) Handle(params GetAllChampionMasteriesParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetAllChampionMasteriesHandler interface for that can handle valid get all champion masteries params
type GetAllChampionMasteriesHandler interface {
	Handle(GetAllChampionMasteriesParams, interface{}) middleware.Responder
}

// NewGetAllChampionMasteries creates a new http.Handler for the get all champion masteries operation
func NewGetAllChampionMasteries(ctx *middleware.Context, handler GetAllChampionMasteriesHandler) *GetAllChampionMasteries {
	return &GetAllChampionMasteries{Context: ctx, Handler: handler}
}

/*GetAllChampionMasteries swagger:route GET /champion-mastery/v4/champion-masteries/by-summoner/{encryptedSummonerId} championMastery getAllChampionMasteries

Get all champion mastery entries sorted by number of champion points descending

*/
type GetAllChampionMasteries struct {
	Context *middleware.Context
	Handler GetAllChampionMasteriesHandler
}

func (o *GetAllChampionMasteries) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAllChampionMasteriesParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
