// Code generated by go-swagger; DO NOT EDIT.

package champion_mastery

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetChampionMasteryParams creates a new GetChampionMasteryParams object
// no default values defined in spec.
func NewGetChampionMasteryParams() GetChampionMasteryParams {

	return GetChampionMasteryParams{}
}

// GetChampionMasteryParams contains all the bound params for the get champion mastery operation
// typically these are obtained from a http.Request
//
// swagger:parameters getChampionMastery
type GetChampionMasteryParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Champion ID
	  Required: true
	  In: path
	*/
	ChampionID int64
	/*Summoner ID associated with the player
	  Required: true
	  In: path
	*/
	EncryptedSummonerID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetChampionMasteryParams() beforehand.
func (o *GetChampionMasteryParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rChampionID, rhkChampionID, _ := route.Params.GetOK("championId")
	if err := o.bindChampionID(rChampionID, rhkChampionID, route.Formats); err != nil {
		res = append(res, err)
	}

	rEncryptedSummonerID, rhkEncryptedSummonerID, _ := route.Params.GetOK("encryptedSummonerId")
	if err := o.bindEncryptedSummonerID(rEncryptedSummonerID, rhkEncryptedSummonerID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindChampionID binds and validates parameter ChampionID from path.
func (o *GetChampionMasteryParams) bindChampionID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("championId", "path", "int64", raw)
	}
	o.ChampionID = value

	return nil
}

// bindEncryptedSummonerID binds and validates parameter EncryptedSummonerID from path.
func (o *GetChampionMasteryParams) bindEncryptedSummonerID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.EncryptedSummonerID = raw

	return nil
}
