// Code generated by go-swagger; DO NOT EDIT.

package champion

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/andresperezl/gol/lolapi/models"
)

// GetChampionInfoOKCode is the HTTP code returned for type GetChampionInfoOK
const GetChampionInfoOKCode int = 200

/*GetChampionInfoOK OK

swagger:response getChampionInfoOK
*/
type GetChampionInfoOK struct {

	/*
	  In: Body
	*/
	Payload *models.ChampionInfo `json:"body,omitempty"`
}

// NewGetChampionInfoOK creates GetChampionInfoOK with default headers values
func NewGetChampionInfoOK() *GetChampionInfoOK {

	return &GetChampionInfoOK{}
}

// WithPayload adds the payload to the get champion info o k response
func (o *GetChampionInfoOK) WithPayload(payload *models.ChampionInfo) *GetChampionInfoOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get champion info o k response
func (o *GetChampionInfoOK) SetPayload(payload *models.ChampionInfo) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetChampionInfoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetChampionInfoBadRequestCode is the HTTP code returned for type GetChampionInfoBadRequest
const GetChampionInfoBadRequestCode int = 400

/*GetChampionInfoBadRequest Bad request

swagger:response getChampionInfoBadRequest
*/
type GetChampionInfoBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetChampionInfoBadRequest creates GetChampionInfoBadRequest with default headers values
func NewGetChampionInfoBadRequest() *GetChampionInfoBadRequest {

	return &GetChampionInfoBadRequest{}
}

// WithPayload adds the payload to the get champion info bad request response
func (o *GetChampionInfoBadRequest) WithPayload(payload *models.Error) *GetChampionInfoBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get champion info bad request response
func (o *GetChampionInfoBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetChampionInfoBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetChampionInfoUnauthorizedCode is the HTTP code returned for type GetChampionInfoUnauthorized
const GetChampionInfoUnauthorizedCode int = 401

/*GetChampionInfoUnauthorized Unauthorized

swagger:response getChampionInfoUnauthorized
*/
type GetChampionInfoUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetChampionInfoUnauthorized creates GetChampionInfoUnauthorized with default headers values
func NewGetChampionInfoUnauthorized() *GetChampionInfoUnauthorized {

	return &GetChampionInfoUnauthorized{}
}

// WithPayload adds the payload to the get champion info unauthorized response
func (o *GetChampionInfoUnauthorized) WithPayload(payload *models.Error) *GetChampionInfoUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get champion info unauthorized response
func (o *GetChampionInfoUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetChampionInfoUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetChampionInfoForbiddenCode is the HTTP code returned for type GetChampionInfoForbidden
const GetChampionInfoForbiddenCode int = 403

/*GetChampionInfoForbidden Forbidden

swagger:response getChampionInfoForbidden
*/
type GetChampionInfoForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetChampionInfoForbidden creates GetChampionInfoForbidden with default headers values
func NewGetChampionInfoForbidden() *GetChampionInfoForbidden {

	return &GetChampionInfoForbidden{}
}

// WithPayload adds the payload to the get champion info forbidden response
func (o *GetChampionInfoForbidden) WithPayload(payload *models.Error) *GetChampionInfoForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get champion info forbidden response
func (o *GetChampionInfoForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetChampionInfoForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetChampionInfoNotFoundCode is the HTTP code returned for type GetChampionInfoNotFound
const GetChampionInfoNotFoundCode int = 404

/*GetChampionInfoNotFound Not found

swagger:response getChampionInfoNotFound
*/
type GetChampionInfoNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetChampionInfoNotFound creates GetChampionInfoNotFound with default headers values
func NewGetChampionInfoNotFound() *GetChampionInfoNotFound {

	return &GetChampionInfoNotFound{}
}

// WithPayload adds the payload to the get champion info not found response
func (o *GetChampionInfoNotFound) WithPayload(payload *models.Error) *GetChampionInfoNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get champion info not found response
func (o *GetChampionInfoNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetChampionInfoNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetChampionInfoMethodNotAllowedCode is the HTTP code returned for type GetChampionInfoMethodNotAllowed
const GetChampionInfoMethodNotAllowedCode int = 405

/*GetChampionInfoMethodNotAllowed Method not allowed

swagger:response getChampionInfoMethodNotAllowed
*/
type GetChampionInfoMethodNotAllowed struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetChampionInfoMethodNotAllowed creates GetChampionInfoMethodNotAllowed with default headers values
func NewGetChampionInfoMethodNotAllowed() *GetChampionInfoMethodNotAllowed {

	return &GetChampionInfoMethodNotAllowed{}
}

// WithPayload adds the payload to the get champion info method not allowed response
func (o *GetChampionInfoMethodNotAllowed) WithPayload(payload *models.Error) *GetChampionInfoMethodNotAllowed {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get champion info method not allowed response
func (o *GetChampionInfoMethodNotAllowed) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetChampionInfoMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetChampionInfoUnsupportedMediaTypeCode is the HTTP code returned for type GetChampionInfoUnsupportedMediaType
const GetChampionInfoUnsupportedMediaTypeCode int = 415

/*GetChampionInfoUnsupportedMediaType Unsopported media type

swagger:response getChampionInfoUnsupportedMediaType
*/
type GetChampionInfoUnsupportedMediaType struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetChampionInfoUnsupportedMediaType creates GetChampionInfoUnsupportedMediaType with default headers values
func NewGetChampionInfoUnsupportedMediaType() *GetChampionInfoUnsupportedMediaType {

	return &GetChampionInfoUnsupportedMediaType{}
}

// WithPayload adds the payload to the get champion info unsupported media type response
func (o *GetChampionInfoUnsupportedMediaType) WithPayload(payload *models.Error) *GetChampionInfoUnsupportedMediaType {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get champion info unsupported media type response
func (o *GetChampionInfoUnsupportedMediaType) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetChampionInfoUnsupportedMediaType) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(415)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetChampionInfoTooManyRequestsCode is the HTTP code returned for type GetChampionInfoTooManyRequests
const GetChampionInfoTooManyRequestsCode int = 429

/*GetChampionInfoTooManyRequests Rate limit Exceeded

swagger:response getChampionInfoTooManyRequests
*/
type GetChampionInfoTooManyRequests struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetChampionInfoTooManyRequests creates GetChampionInfoTooManyRequests with default headers values
func NewGetChampionInfoTooManyRequests() *GetChampionInfoTooManyRequests {

	return &GetChampionInfoTooManyRequests{}
}

// WithPayload adds the payload to the get champion info too many requests response
func (o *GetChampionInfoTooManyRequests) WithPayload(payload *models.Error) *GetChampionInfoTooManyRequests {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get champion info too many requests response
func (o *GetChampionInfoTooManyRequests) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetChampionInfoTooManyRequests) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(429)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetChampionInfoInternalServerErrorCode is the HTTP code returned for type GetChampionInfoInternalServerError
const GetChampionInfoInternalServerErrorCode int = 500

/*GetChampionInfoInternalServerError Internal server error

swagger:response getChampionInfoInternalServerError
*/
type GetChampionInfoInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetChampionInfoInternalServerError creates GetChampionInfoInternalServerError with default headers values
func NewGetChampionInfoInternalServerError() *GetChampionInfoInternalServerError {

	return &GetChampionInfoInternalServerError{}
}

// WithPayload adds the payload to the get champion info internal server error response
func (o *GetChampionInfoInternalServerError) WithPayload(payload *models.Error) *GetChampionInfoInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get champion info internal server error response
func (o *GetChampionInfoInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetChampionInfoInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetChampionInfoBadGatewayCode is the HTTP code returned for type GetChampionInfoBadGateway
const GetChampionInfoBadGatewayCode int = 502

/*GetChampionInfoBadGateway Bad gateway

swagger:response getChampionInfoBadGateway
*/
type GetChampionInfoBadGateway struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetChampionInfoBadGateway creates GetChampionInfoBadGateway with default headers values
func NewGetChampionInfoBadGateway() *GetChampionInfoBadGateway {

	return &GetChampionInfoBadGateway{}
}

// WithPayload adds the payload to the get champion info bad gateway response
func (o *GetChampionInfoBadGateway) WithPayload(payload *models.Error) *GetChampionInfoBadGateway {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get champion info bad gateway response
func (o *GetChampionInfoBadGateway) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetChampionInfoBadGateway) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(502)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetChampionInfoServiceUnavailableCode is the HTTP code returned for type GetChampionInfoServiceUnavailable
const GetChampionInfoServiceUnavailableCode int = 503

/*GetChampionInfoServiceUnavailable Service Unavailable

swagger:response getChampionInfoServiceUnavailable
*/
type GetChampionInfoServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetChampionInfoServiceUnavailable creates GetChampionInfoServiceUnavailable with default headers values
func NewGetChampionInfoServiceUnavailable() *GetChampionInfoServiceUnavailable {

	return &GetChampionInfoServiceUnavailable{}
}

// WithPayload adds the payload to the get champion info service unavailable response
func (o *GetChampionInfoServiceUnavailable) WithPayload(payload *models.Error) *GetChampionInfoServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get champion info service unavailable response
func (o *GetChampionInfoServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetChampionInfoServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetChampionInfoGatewayTimeoutCode is the HTTP code returned for type GetChampionInfoGatewayTimeout
const GetChampionInfoGatewayTimeoutCode int = 504

/*GetChampionInfoGatewayTimeout Gateway timeout

swagger:response getChampionInfoGatewayTimeout
*/
type GetChampionInfoGatewayTimeout struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetChampionInfoGatewayTimeout creates GetChampionInfoGatewayTimeout with default headers values
func NewGetChampionInfoGatewayTimeout() *GetChampionInfoGatewayTimeout {

	return &GetChampionInfoGatewayTimeout{}
}

// WithPayload adds the payload to the get champion info gateway timeout response
func (o *GetChampionInfoGatewayTimeout) WithPayload(payload *models.Error) *GetChampionInfoGatewayTimeout {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get champion info gateway timeout response
func (o *GetChampionInfoGatewayTimeout) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetChampionInfoGatewayTimeout) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(504)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
