// Code generated by go-swagger; DO NOT EDIT.

package champion

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetChampionInfoHandlerFunc turns a function with the right signature into a get champion info handler
type GetChampionInfoHandlerFunc func(GetChampionInfoParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetChampionInfoHandlerFunc) Handle(params GetChampionInfoParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetChampionInfoHandler interface for that can handle valid get champion info params
type GetChampionInfoHandler interface {
	Handle(GetChampionInfoParams, interface{}) middleware.Responder
}

// NewGetChampionInfo creates a new http.Handler for the get champion info operation
func NewGetChampionInfo(ctx *middleware.Context, handler GetChampionInfoHandler) *GetChampionInfo {
	return &GetChampionInfo{Context: ctx, Handler: handler}
}

/*GetChampionInfo swagger:route GET /platform/v3/champion-rotations champion getChampionInfo

Returns champion rotations, including free-to-play and low-level free-to-play rotations

*/
type GetChampionInfo struct {
	Context *middleware.Context
	Handler GetChampionInfoHandler
}

func (o *GetChampionInfo) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetChampionInfoParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
