// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// TokensEarned The token earned for this champion to levelup
// swagger:model TokensEarned
type TokensEarned int32

// Validate validates this tokens earned
func (m TokensEarned) Validate(formats strfmt.Registry) error {
	return nil
}
