// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// ChampionPoints Total number of champion points for this player and champion combination - they are used to determine championLevel
// swagger:model ChampionPoints
type ChampionPoints int32

// Validate validates this champion points
func (m ChampionPoints) Validate(formats strfmt.Registry) error {
	return nil
}
