// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// ChampionLevel Champion level for specified player and champion combination
// swagger:model ChampionLevel
type ChampionLevel int32

// Validate validates this champion level
func (m ChampionLevel) Validate(formats strfmt.Registry) error {
	return nil
}
