// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ChampionInfo champion info
// swagger:model ChampionInfo
type ChampionInfo struct {

	// free champion ids
	FreeChampionIds []int32 `json:"freeChampionIds"`

	// free champion ids for new players
	FreeChampionIdsForNewPlayers []int32 `json:"freeChampionIdsForNewPlayers"`

	// max new player level
	MaxNewPlayerLevel int32 `json:"maxNewPlayerLevel,omitempty"`
}

// Validate validates this champion info
func (m *ChampionInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ChampionInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChampionInfo) UnmarshalBinary(b []byte) error {
	var res ChampionInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
