// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// ChampionPointsSinceLastLevel Number of points earned since current level has been achieved
// swagger:model ChampionPointsSinceLastLevel
type ChampionPointsSinceLastLevel int64

// Validate validates this champion points since last level
func (m ChampionPointsSinceLastLevel) Validate(formats strfmt.Registry) error {
	return nil
}
