// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// ChestGranted Is chest granted for this champion or not in current season
// swagger:model ChestGranted
type ChestGranted bool

// Validate validates this chest granted
func (m ChestGranted) Validate(formats strfmt.Registry) error {
	return nil
}
