// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// LastPlayTime Last time this champion was played by this player - in Unix milliseconds time format
// swagger:model LastPlayTime
type LastPlayTime int64

// Validate validates this last play time
func (m LastPlayTime) Validate(formats strfmt.Registry) error {
	return nil
}
