// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	errors "github.com/go-openapi/errors"
	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	security "github.com/go-openapi/runtime/security"
	spec "github.com/go-openapi/spec"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/andresperezl/gol/test/restapi/operations/champion"
	"github.com/andresperezl/gol/test/restapi/operations/champion_mastery"
)

// NewTestserverAPI creates a new Testserver instance
func NewTestserverAPI(spec *loads.Document) *TestserverAPI {
	return &TestserverAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		ServerShutdown:      func() {},
		spec:                spec,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,
		JSONConsumer:        runtime.JSONConsumer(),
		JSONProducer:        runtime.JSONProducer(),
		ChampionMasteryGetAllChampionMasteriesHandler: champion_mastery.GetAllChampionMasteriesHandlerFunc(func(params champion_mastery.GetAllChampionMasteriesParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation ChampionMasteryGetAllChampionMasteries has not yet been implemented")
		}),
		ChampionGetChampionInfoHandler: champion.GetChampionInfoHandlerFunc(func(params champion.GetChampionInfoParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation ChampionGetChampionInfo has not yet been implemented")
		}),
		ChampionMasteryGetChampionMasteryHandler: champion_mastery.GetChampionMasteryHandlerFunc(func(params champion_mastery.GetChampionMasteryParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation ChampionMasteryGetChampionMastery has not yet been implemented")
		}),
		ChampionMasteryGetChampionMasteryScoreHandler: champion_mastery.GetChampionMasteryScoreHandlerFunc(func(params champion_mastery.GetChampionMasteryScoreParams, principal interface{}) middleware.Responder {
			return middleware.NotImplemented("operation ChampionMasteryGetChampionMasteryScore has not yet been implemented")
		}),

		// Applies when the "X-Riot-Token" header is set
		APIKeyHeaderAuth: func(token string) (interface{}, error) {
			return nil, errors.NotImplemented("api key auth (APIKeyHeader) X-Riot-Token from header param [X-Riot-Token] has not yet been implemented")
		},
		// Applies when the "api_key" query is set
		APIKeyQueryParamAuth: func(token string) (interface{}, error) {
			return nil, errors.NotImplemented("api key auth (APIKeyQueryParam) api_key from query param [api_key] has not yet been implemented")
		},

		// default authorizer is authorized meaning no requests are blocked
		APIAuthorizer: security.Authorized(),
	}
}

/*TestserverAPI the testserver API */
type TestserverAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator
	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator
	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for a "application/json" mime type
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for a "application/json" mime type
	JSONProducer runtime.Producer

	// APIKeyHeaderAuth registers a function that takes a token and returns a principal
	// it performs authentication based on an api key X-Riot-Token provided in the header
	APIKeyHeaderAuth func(string) (interface{}, error)

	// APIKeyQueryParamAuth registers a function that takes a token and returns a principal
	// it performs authentication based on an api key api_key provided in the query
	APIKeyQueryParamAuth func(string) (interface{}, error)

	// APIAuthorizer provides access control (ACL/RBAC/ABAC) by providing access to the request and authenticated principal
	APIAuthorizer runtime.Authorizer

	// ChampionMasteryGetAllChampionMasteriesHandler sets the operation handler for the get all champion masteries operation
	ChampionMasteryGetAllChampionMasteriesHandler champion_mastery.GetAllChampionMasteriesHandler
	// ChampionGetChampionInfoHandler sets the operation handler for the get champion info operation
	ChampionGetChampionInfoHandler champion.GetChampionInfoHandler
	// ChampionMasteryGetChampionMasteryHandler sets the operation handler for the get champion mastery operation
	ChampionMasteryGetChampionMasteryHandler champion_mastery.GetChampionMasteryHandler
	// ChampionMasteryGetChampionMasteryScoreHandler sets the operation handler for the get champion mastery score operation
	ChampionMasteryGetChampionMasteryScoreHandler champion_mastery.GetChampionMasteryScoreHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *TestserverAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *TestserverAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *TestserverAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *TestserverAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *TestserverAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *TestserverAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *TestserverAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the TestserverAPI
func (o *TestserverAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.APIKeyHeaderAuth == nil {
		unregistered = append(unregistered, "XRiotTokenAuth")
	}

	if o.APIKeyQueryParamAuth == nil {
		unregistered = append(unregistered, "APIKeyAuth")
	}

	if o.ChampionMasteryGetAllChampionMasteriesHandler == nil {
		unregistered = append(unregistered, "champion_mastery.GetAllChampionMasteriesHandler")
	}

	if o.ChampionGetChampionInfoHandler == nil {
		unregistered = append(unregistered, "champion.GetChampionInfoHandler")
	}

	if o.ChampionMasteryGetChampionMasteryHandler == nil {
		unregistered = append(unregistered, "champion_mastery.GetChampionMasteryHandler")
	}

	if o.ChampionMasteryGetChampionMasteryScoreHandler == nil {
		unregistered = append(unregistered, "champion_mastery.GetChampionMasteryScoreHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *TestserverAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *TestserverAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {

	result := make(map[string]runtime.Authenticator)
	for name := range schemes {
		switch name {

		case "APIKeyHeader":

			scheme := schemes[name]
			result[name] = o.APIKeyAuthenticator(scheme.Name, scheme.In, o.APIKeyHeaderAuth)

		case "APIKeyQueryParam":

			scheme := schemes[name]
			result[name] = o.APIKeyAuthenticator(scheme.Name, scheme.In, o.APIKeyQueryParamAuth)

		}
	}
	return result

}

// Authorizer returns the registered authorizer
func (o *TestserverAPI) Authorizer() runtime.Authorizer {

	return o.APIAuthorizer

}

// ConsumersFor gets the consumers for the specified media types
func (o *TestserverAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {

	result := make(map[string]runtime.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONConsumer

		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *TestserverAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {

	result := make(map[string]runtime.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONProducer

		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *TestserverAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the testserver API
func (o *TestserverAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *TestserverAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/champion-mastery/v4/champion-masteries/by-summoner/{encryptedSummonerId}"] = champion_mastery.NewGetAllChampionMasteries(o.context, o.ChampionMasteryGetAllChampionMasteriesHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/platform/v3/champion-rotations"] = champion.NewGetChampionInfo(o.context, o.ChampionGetChampionInfoHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/champion-mastery/v4/champion-masteries/by-summoner/{encryptedSummonerId}/by-champion/{championId}"] = champion_mastery.NewGetChampionMastery(o.context, o.ChampionMasteryGetChampionMasteryHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/champion-mastery/v4/scores/by-summoner/{encryptedSummonerId}"] = champion_mastery.NewGetChampionMasteryScore(o.context, o.ChampionMasteryGetChampionMasteryScoreHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *TestserverAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *TestserverAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *TestserverAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *TestserverAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}
