// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Riot League of Legends API
Terms Of Service:

https://developer.riotgames.com/terms


    Schemes:
      https
    Host: localhost
    BasePath: /lol
    Version: v4

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
