// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Riot League of Legends API",
    "termsOfService": "https://developer.riotgames.com/terms",
    "version": "v4"
  },
  "basePath": "/lol",
  "paths": {
    "/champion-mastery/v4/champion-masteries/by-summoner/{encryptedSummonerId}": {
      "get": {
        "tags": [
          "championMastery"
        ],
        "summary": "Get all champion mastery entries sorted by number of champion points descending",
        "externalDocs": {
          "url": "https://developer.riotgames.com/apis#champion-mastery-v4/GET_getAllChampionMasteries"
        },
        "operationId": "getAllChampionMasteries",
        "parameters": [
          {
            "$ref": "#/parameters/encryptedSummonerId"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/ListChampionMastery"
            }
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "401": {
            "$ref": "#/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/responses/Forbidden"
          },
          "404": {
            "$ref": "#/responses/NotFound"
          },
          "405": {
            "$ref": "#/responses/MethodNotAllowed"
          },
          "415": {
            "$ref": "#/responses/UnsopportedMediaType"
          },
          "429": {
            "$ref": "#/responses/RateLimitExceeded"
          },
          "500": {
            "$ref": "#/responses/IntenalServerError"
          },
          "502": {
            "$ref": "#/responses/BadGateway"
          },
          "503": {
            "$ref": "#/responses/ServiceUnavailable"
          },
          "504": {
            "$ref": "#/responses/GatewayTimeout"
          }
        }
      }
    },
    "/champion-mastery/v4/champion-masteries/by-summoner/{encryptedSummonerId}/by-champion/{championId}": {
      "get": {
        "tags": [
          "championMastery"
        ],
        "summary": "Get a champion mastery by player ID and champion ID",
        "externalDocs": {
          "url": "https://developer.riotgames.com/apis#champion-mastery-v4/GET_getChampionMastery"
        },
        "operationId": "getChampionMastery",
        "parameters": [
          {
            "$ref": "#/parameters/encryptedSummonerId"
          },
          {
            "$ref": "#/parameters/championId"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/ChampionMastery"
            }
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "401": {
            "$ref": "#/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/responses/Forbidden"
          },
          "404": {
            "$ref": "#/responses/NotFound"
          },
          "405": {
            "$ref": "#/responses/MethodNotAllowed"
          },
          "415": {
            "$ref": "#/responses/UnsopportedMediaType"
          },
          "429": {
            "$ref": "#/responses/RateLimitExceeded"
          },
          "500": {
            "$ref": "#/responses/IntenalServerError"
          },
          "502": {
            "$ref": "#/responses/BadGateway"
          },
          "503": {
            "$ref": "#/responses/ServiceUnavailable"
          },
          "504": {
            "$ref": "#/responses/GatewayTimeout"
          }
        }
      }
    },
    "/champion-mastery/v4/scores/by-summoner/{encryptedSummonerId}": {
      "get": {
        "tags": [
          "championMastery"
        ],
        "summary": "Get a champion mastery by player ID and champion ID",
        "externalDocs": {
          "url": "https://developer.riotgames.com/apis#champion-mastery-v4/GET_getChampionMasteryScore"
        },
        "operationId": "getChampionMasteryScore",
        "parameters": [
          {
            "$ref": "#/parameters/encryptedSummonerId"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "401": {
            "$ref": "#/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/responses/Forbidden"
          },
          "404": {
            "$ref": "#/responses/NotFound"
          },
          "405": {
            "$ref": "#/responses/MethodNotAllowed"
          },
          "415": {
            "$ref": "#/responses/UnsopportedMediaType"
          },
          "429": {
            "$ref": "#/responses/RateLimitExceeded"
          },
          "500": {
            "$ref": "#/responses/IntenalServerError"
          },
          "502": {
            "$ref": "#/responses/BadGateway"
          },
          "503": {
            "$ref": "#/responses/ServiceUnavailable"
          },
          "504": {
            "$ref": "#/responses/GatewayTimeout"
          }
        }
      }
    },
    "/platform/v3/champion-rotations": {
      "get": {
        "tags": [
          "champion"
        ],
        "summary": "Returns champion rotations, including free-to-play and low-level free-to-play rotations",
        "externalDocs": {
          "url": "https://developer.riotgames.com/apis#champion-v3/GET_getChampionInfo"
        },
        "operationId": "getChampionInfo",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/ChampionInfo"
            }
          },
          "400": {
            "$ref": "#/responses/BadRequest"
          },
          "401": {
            "$ref": "#/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/responses/Forbidden"
          },
          "404": {
            "$ref": "#/responses/NotFound"
          },
          "405": {
            "$ref": "#/responses/MethodNotAllowed"
          },
          "415": {
            "$ref": "#/responses/UnsopportedMediaType"
          },
          "429": {
            "$ref": "#/responses/RateLimitExceeded"
          },
          "500": {
            "$ref": "#/responses/IntenalServerError"
          },
          "502": {
            "$ref": "#/responses/BadGateway"
          },
          "503": {
            "$ref": "#/responses/ServiceUnavailable"
          },
          "504": {
            "$ref": "#/responses/GatewayTimeout"
          }
        }
      }
    }
  },
  "definitions": {
    "ChampionId": {
      "description": "Champion ID",
      "type": "integer",
      "format": "int64",
      "readOnly": true
    },
    "ChampionInfo": {
      "type": "object",
      "properties": {
        "freeChampionIds": {
          "type": "array",
          "items": {
            "type": "integer",
            "format": "int32"
          }
        },
        "freeChampionIdsForNewPlayers": {
          "type": "array",
          "items": {
            "type": "integer",
            "format": "int32"
          }
        },
        "maxNewPlayerLevel": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "ChampionLevel": {
      "description": "Champion level for specified player and champion combination",
      "type": "integer",
      "format": "int32",
      "readOnly": true
    },
    "ChampionMastery": {
      "description": " Contains single Champion Mastery information for player and champion combination",
      "type": "object",
      "properties": {
        "championId": {
          "$ref": "#/definitions/ChampionId"
        },
        "championLevel": {
          "$ref": "#/definitions/ChampionLevel"
        },
        "championPoints": {
          "$ref": "#/definitions/ChampionPoints"
        },
        "championPointsSinceLastLevel": {
          "$ref": "#/definitions/ChampionPointsSinceLastLevel"
        },
        "championPointsUntilNextLevel": {
          "$ref": "#/definitions/ChampionPointsUntilNextLevel"
        },
        "chestGranted": {
          "$ref": "#/definitions/ChestGranted"
        },
        "lastPlayTime": {
          "$ref": "#/definitions/LastPlayTime"
        },
        "summonerId": {
          "$ref": "#/definitions/EncryptedSummonerId"
        },
        "tokensEarned": {
          "$ref": "#/definitions/TokensEarned"
        }
      },
      "readOnly": true
    },
    "ChampionPoints": {
      "description": "Total number of champion points for this player and champion combination - they are used to determine championLevel",
      "type": "integer",
      "format": "int32",
      "readOnly": true
    },
    "ChampionPointsSinceLastLevel": {
      "description": "Number of points earned since current level has been achieved",
      "type": "integer",
      "format": "int64",
      "readOnly": true
    },
    "ChampionPointsUntilNextLevel": {
      "description": "Number of points needed to achieve next level. Zero if player reached maximum champion level for this champion",
      "type": "integer",
      "format": "int64",
      "readOnly": true
    },
    "ChestGranted": {
      "description": "Is chest granted for this champion or not in current season",
      "type": "boolean",
      "readOnly": true
    },
    "EncryptedSummonerId": {
      "description": "Summoner ID (Encrypted)",
      "type": "string",
      "readOnly": true
    },
    "Error": {
      "type": "object",
      "properties": {
        "status": {
          "$ref": "#/definitions/Status"
        }
      },
      "readOnly": true
    },
    "LastPlayTime": {
      "description": "Last time this champion was played by this player - in Unix milliseconds time format",
      "type": "integer",
      "format": "int64",
      "readOnly": true
    },
    "ListChampionMastery": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/ChampionMastery"
      },
      "readOnly": true
    },
    "Status": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string",
          "readOnly": true
        },
        "status_code": {
          "type": "integer",
          "format": "int32",
          "readOnly": true
        }
      },
      "readOnly": true
    },
    "TokensEarned": {
      "description": "The token earned for this champion to levelup",
      "type": "integer",
      "format": "int32",
      "readOnly": true
    }
  },
  "parameters": {
    "championId": {
      "type": "integer",
      "format": "int64",
      "description": "Champion ID",
      "name": "championId",
      "in": "path",
      "required": true
    },
    "encryptedSummonerId": {
      "type": "string",
      "description": "Summoner ID associated with the player",
      "name": "encryptedSummonerId",
      "in": "path",
      "required": true
    }
  },
  "responses": {
    "401": {
      "description": "Unauthorized",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "403": {
      "description": "Forbidden",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "BadGateway": {
      "description": "Bad gateway",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "BadRequest": {
      "description": "Bad request",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "Forbidden": {
      "description": "Forbidden",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "GatewayTimeout": {
      "description": "Gateway timeout",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "IntenalServerError": {
      "description": "Internal server error",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "MethodNotAllowed": {
      "description": "Method not allowed",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "NotFound": {
      "description": "Not found",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "RateLimitExceeded": {
      "description": "Rate limit Exceeded",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "ServiceUnavailable": {
      "description": "Service Unavailable",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "Unauthorized": {
      "description": "Unauthorized",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "UnsopportedMediaType": {
      "description": "Unsopported media type",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    }
  },
  "securityDefinitions": {
    "APIKeyHeader": {
      "type": "apiKey",
      "name": "X-Riot-Token",
      "in": "header"
    },
    "APIKeyQueryParam": {
      "type": "apiKey",
      "name": "api_key",
      "in": "query"
    }
  },
  "security": [
    {
      "APIKeyHeader": []
    },
    {
      "APIKeyQueryParam": []
    }
  ],
  "tags": [
    {
      "name": "championMastery",
      "externalDocs": {
        "url": "https://developer.riotgames.com/apis#champion-mastery-v4"
      }
    },
    {
      "name": "champion",
      "externalDocs": {
        "url": "https://developer.riotgames.com/apis#champion-v3"
      }
    }
  ],
  "externalDocs": {
    "url": "https://developer.riotgames.com/apis"
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Riot League of Legends API",
    "termsOfService": "https://developer.riotgames.com/terms",
    "version": "v4"
  },
  "basePath": "/lol",
  "paths": {
    "/champion-mastery/v4/champion-masteries/by-summoner/{encryptedSummonerId}": {
      "get": {
        "tags": [
          "championMastery"
        ],
        "summary": "Get all champion mastery entries sorted by number of champion points descending",
        "externalDocs": {
          "url": "https://developer.riotgames.com/apis#champion-mastery-v4/GET_getAllChampionMasteries"
        },
        "operationId": "getAllChampionMasteries",
        "parameters": [
          {
            "type": "string",
            "description": "Summoner ID associated with the player",
            "name": "encryptedSummonerId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/ListChampionMastery"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "405": {
            "description": "Method not allowed",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "415": {
            "description": "Unsopported media type",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "429": {
            "description": "Rate limit Exceeded",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "502": {
            "description": "Bad gateway",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "503": {
            "description": "Service Unavailable",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "504": {
            "description": "Gateway timeout",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/champion-mastery/v4/champion-masteries/by-summoner/{encryptedSummonerId}/by-champion/{championId}": {
      "get": {
        "tags": [
          "championMastery"
        ],
        "summary": "Get a champion mastery by player ID and champion ID",
        "externalDocs": {
          "url": "https://developer.riotgames.com/apis#champion-mastery-v4/GET_getChampionMastery"
        },
        "operationId": "getChampionMastery",
        "parameters": [
          {
            "type": "string",
            "description": "Summoner ID associated with the player",
            "name": "encryptedSummonerId",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "format": "int64",
            "description": "Champion ID",
            "name": "championId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/ChampionMastery"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "405": {
            "description": "Method not allowed",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "415": {
            "description": "Unsopported media type",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "429": {
            "description": "Rate limit Exceeded",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "502": {
            "description": "Bad gateway",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "503": {
            "description": "Service Unavailable",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "504": {
            "description": "Gateway timeout",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/champion-mastery/v4/scores/by-summoner/{encryptedSummonerId}": {
      "get": {
        "tags": [
          "championMastery"
        ],
        "summary": "Get a champion mastery by player ID and champion ID",
        "externalDocs": {
          "url": "https://developer.riotgames.com/apis#champion-mastery-v4/GET_getChampionMasteryScore"
        },
        "operationId": "getChampionMasteryScore",
        "parameters": [
          {
            "type": "string",
            "description": "Summoner ID associated with the player",
            "name": "encryptedSummonerId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "405": {
            "description": "Method not allowed",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "415": {
            "description": "Unsopported media type",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "429": {
            "description": "Rate limit Exceeded",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "502": {
            "description": "Bad gateway",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "503": {
            "description": "Service Unavailable",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "504": {
            "description": "Gateway timeout",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/platform/v3/champion-rotations": {
      "get": {
        "tags": [
          "champion"
        ],
        "summary": "Returns champion rotations, including free-to-play and low-level free-to-play rotations",
        "externalDocs": {
          "url": "https://developer.riotgames.com/apis#champion-v3/GET_getChampionInfo"
        },
        "operationId": "getChampionInfo",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/ChampionInfo"
            }
          },
          "400": {
            "description": "Bad request",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "403": {
            "description": "Forbidden",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "404": {
            "description": "Not found",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "405": {
            "description": "Method not allowed",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "415": {
            "description": "Unsopported media type",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "429": {
            "description": "Rate limit Exceeded",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal server error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "502": {
            "description": "Bad gateway",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "503": {
            "description": "Service Unavailable",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "504": {
            "description": "Gateway timeout",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ChampionId": {
      "description": "Champion ID",
      "type": "integer",
      "format": "int64",
      "readOnly": true
    },
    "ChampionInfo": {
      "type": "object",
      "properties": {
        "freeChampionIds": {
          "type": "array",
          "items": {
            "type": "integer",
            "format": "int32"
          }
        },
        "freeChampionIdsForNewPlayers": {
          "type": "array",
          "items": {
            "type": "integer",
            "format": "int32"
          }
        },
        "maxNewPlayerLevel": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "ChampionLevel": {
      "description": "Champion level for specified player and champion combination",
      "type": "integer",
      "format": "int32",
      "readOnly": true
    },
    "ChampionMastery": {
      "description": " Contains single Champion Mastery information for player and champion combination",
      "type": "object",
      "properties": {
        "championId": {
          "$ref": "#/definitions/ChampionId"
        },
        "championLevel": {
          "$ref": "#/definitions/ChampionLevel"
        },
        "championPoints": {
          "$ref": "#/definitions/ChampionPoints"
        },
        "championPointsSinceLastLevel": {
          "$ref": "#/definitions/ChampionPointsSinceLastLevel"
        },
        "championPointsUntilNextLevel": {
          "$ref": "#/definitions/ChampionPointsUntilNextLevel"
        },
        "chestGranted": {
          "$ref": "#/definitions/ChestGranted"
        },
        "lastPlayTime": {
          "$ref": "#/definitions/LastPlayTime"
        },
        "summonerId": {
          "$ref": "#/definitions/EncryptedSummonerId"
        },
        "tokensEarned": {
          "$ref": "#/definitions/TokensEarned"
        }
      },
      "readOnly": true
    },
    "ChampionPoints": {
      "description": "Total number of champion points for this player and champion combination - they are used to determine championLevel",
      "type": "integer",
      "format": "int32",
      "readOnly": true
    },
    "ChampionPointsSinceLastLevel": {
      "description": "Number of points earned since current level has been achieved",
      "type": "integer",
      "format": "int64",
      "readOnly": true
    },
    "ChampionPointsUntilNextLevel": {
      "description": "Number of points needed to achieve next level. Zero if player reached maximum champion level for this champion",
      "type": "integer",
      "format": "int64",
      "readOnly": true
    },
    "ChestGranted": {
      "description": "Is chest granted for this champion or not in current season",
      "type": "boolean",
      "readOnly": true
    },
    "EncryptedSummonerId": {
      "description": "Summoner ID (Encrypted)",
      "type": "string",
      "readOnly": true
    },
    "Error": {
      "type": "object",
      "properties": {
        "status": {
          "$ref": "#/definitions/Status"
        }
      },
      "readOnly": true
    },
    "LastPlayTime": {
      "description": "Last time this champion was played by this player - in Unix milliseconds time format",
      "type": "integer",
      "format": "int64",
      "readOnly": true
    },
    "ListChampionMastery": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/ChampionMastery"
      },
      "readOnly": true
    },
    "Status": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string",
          "readOnly": true
        },
        "status_code": {
          "type": "integer",
          "format": "int32",
          "readOnly": true
        }
      },
      "readOnly": true
    },
    "TokensEarned": {
      "description": "The token earned for this champion to levelup",
      "type": "integer",
      "format": "int32",
      "readOnly": true
    }
  },
  "parameters": {
    "championId": {
      "type": "integer",
      "format": "int64",
      "description": "Champion ID",
      "name": "championId",
      "in": "path",
      "required": true
    },
    "encryptedSummonerId": {
      "type": "string",
      "description": "Summoner ID associated with the player",
      "name": "encryptedSummonerId",
      "in": "path",
      "required": true
    }
  },
  "responses": {
    "401": {
      "description": "Unauthorized",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "403": {
      "description": "Forbidden",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "BadGateway": {
      "description": "Bad gateway",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "BadRequest": {
      "description": "Bad request",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "Forbidden": {
      "description": "Forbidden",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "GatewayTimeout": {
      "description": "Gateway timeout",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "IntenalServerError": {
      "description": "Internal server error",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "MethodNotAllowed": {
      "description": "Method not allowed",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "NotFound": {
      "description": "Not found",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "RateLimitExceeded": {
      "description": "Rate limit Exceeded",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "ServiceUnavailable": {
      "description": "Service Unavailable",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "Unauthorized": {
      "description": "Unauthorized",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    },
    "UnsopportedMediaType": {
      "description": "Unsopported media type",
      "schema": {
        "$ref": "#/definitions/Error"
      }
    }
  },
  "securityDefinitions": {
    "APIKeyHeader": {
      "type": "apiKey",
      "name": "X-Riot-Token",
      "in": "header"
    },
    "APIKeyQueryParam": {
      "type": "apiKey",
      "name": "api_key",
      "in": "query"
    }
  },
  "security": [
    {
      "APIKeyHeader": []
    },
    {
      "APIKeyQueryParam": []
    }
  ],
  "tags": [
    {
      "name": "championMastery",
      "externalDocs": {
        "url": "https://developer.riotgames.com/apis#champion-mastery-v4"
      }
    },
    {
      "name": "champion",
      "externalDocs": {
        "url": "https://developer.riotgames.com/apis#champion-v3"
      }
    }
  ],
  "externalDocs": {
    "url": "https://developer.riotgames.com/apis"
  }
}`))
}
