package champion_mastery

import (
	"encoding/json"
	"github.com/andresperezl/gol/models"
	"github.com/andresperezl/gol/test/restapi/operations/champion_mastery"
	"github.com/go-openapi/runtime/middleware"
	"strings"
)

const RawData = `[
    {
        "championLevel": 6,
        "chestGranted": true,
        "championPoints": 75378,
        "championPointsSinceLastLevel": 53778,
        "championPointsUntilNextLevel": 0,
        "summonerId": "test",
        "tokensEarned": 1,
        "championId": 12,
        "lastPlayTime": 1567724912000
    },
    {
        "championLevel": 5,
        "chestGranted": false,
        "championPoints": 45702,
        "championPointsSinceLastLevel": 24102,
        "championPointsUntilNextLevel": 0,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 31,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 5,
        "chestGranted": false,
        "championPoints": 45185,
        "championPointsSinceLastLevel": 23585,
        "championPointsUntilNextLevel": 0,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 102,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 6,
        "chestGranted": true,
        "championPoints": 45167,
        "championPointsSinceLastLevel": 23567,
        "championPointsUntilNextLevel": 0,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 32,
        "lastPlayTime": 1567826742000
    },
    {
        "championLevel": 5,
        "chestGranted": false,
        "championPoints": 22922,
        "championPointsSinceLastLevel": 1322,
        "championPointsUntilNextLevel": 0,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 201,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 4,
        "chestGranted": false,
        "championPoints": 21463,
        "championPointsSinceLastLevel": 8863,
        "championPointsUntilNextLevel": 137,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 15,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 4,
        "chestGranted": false,
        "championPoints": 21251,
        "championPointsSinceLastLevel": 8651,
        "championPointsUntilNextLevel": 349,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 57,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 4,
        "chestGranted": false,
        "championPoints": 20880,
        "championPointsSinceLastLevel": 8280,
        "championPointsUntilNextLevel": 720,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 20,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 4,
        "chestGranted": false,
        "championPoints": 19901,
        "championPointsSinceLastLevel": 7301,
        "championPointsUntilNextLevel": 1699,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 45,
        "lastPlayTime": 1563842386000
    },
    {
        "championLevel": 4,
        "chestGranted": false,
        "championPoints": 19152,
        "championPointsSinceLastLevel": 6552,
        "championPointsUntilNextLevel": 2448,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 36,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 4,
        "chestGranted": false,
        "championPoints": 15377,
        "championPointsSinceLastLevel": 2777,
        "championPointsUntilNextLevel": 6223,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 18,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 4,
        "chestGranted": false,
        "championPoints": 15144,
        "championPointsSinceLastLevel": 2544,
        "championPointsUntilNextLevel": 6456,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 25,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 4,
        "chestGranted": false,
        "championPoints": 14194,
        "championPointsSinceLastLevel": 1594,
        "championPointsUntilNextLevel": 7406,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 37,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 4,
        "chestGranted": false,
        "championPoints": 13655,
        "championPointsSinceLastLevel": 1055,
        "championPointsUntilNextLevel": 7945,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 154,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 3,
        "chestGranted": false,
        "championPoints": 12342,
        "championPointsSinceLastLevel": 6342,
        "championPointsUntilNextLevel": 258,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 16,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 3,
        "chestGranted": false,
        "championPoints": 11794,
        "championPointsSinceLastLevel": 5794,
        "championPointsUntilNextLevel": 806,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 21,
        "lastPlayTime": 1567731772000
    },
    {
        "championLevel": 3,
        "chestGranted": false,
        "championPoints": 10672,
        "championPointsSinceLastLevel": 4672,
        "championPointsUntilNextLevel": 1928,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 51,
        "lastPlayTime": 1567570094000
    },
    {
        "championLevel": 3,
        "chestGranted": false,
        "championPoints": 9590,
        "championPointsSinceLastLevel": 3590,
        "championPointsUntilNextLevel": 3010,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 72,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 3,
        "chestGranted": false,
        "championPoints": 9418,
        "championPointsSinceLastLevel": 3418,
        "championPointsUntilNextLevel": 3182,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 110,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 3,
        "chestGranted": false,
        "championPoints": 9411,
        "championPointsSinceLastLevel": 3411,
        "championPointsUntilNextLevel": 3189,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 81,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 3,
        "chestGranted": false,
        "championPoints": 8958,
        "championPointsSinceLastLevel": 2958,
        "championPointsUntilNextLevel": 3642,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 203,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 3,
        "chestGranted": true,
        "championPoints": 8315,
        "championPointsSinceLastLevel": 2315,
        "championPointsUntilNextLevel": 4285,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 56,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 3,
        "chestGranted": false,
        "championPoints": 7942,
        "championPointsSinceLastLevel": 1942,
        "championPointsUntilNextLevel": 4658,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 41,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 3,
        "chestGranted": false,
        "championPoints": 7440,
        "championPointsSinceLastLevel": 1440,
        "championPointsUntilNextLevel": 5160,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 96,
        "lastPlayTime": 1567125375000
    },
    {
        "championLevel": 3,
        "chestGranted": false,
        "championPoints": 7426,
        "championPointsSinceLastLevel": 1426,
        "championPointsUntilNextLevel": 5174,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 40,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 3,
        "chestGranted": true,
        "championPoints": 7258,
        "championPointsSinceLastLevel": 1258,
        "championPointsUntilNextLevel": 5342,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 33,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 3,
        "chestGranted": false,
        "championPoints": 7241,
        "championPointsSinceLastLevel": 1241,
        "championPointsUntilNextLevel": 5359,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 11,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 3,
        "chestGranted": false,
        "championPoints": 7198,
        "championPointsSinceLastLevel": 1198,
        "championPointsUntilNextLevel": 5402,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 99,
        "lastPlayTime": 1567558588000
    },
    {
        "championLevel": 3,
        "chestGranted": false,
        "championPoints": 6891,
        "championPointsSinceLastLevel": 891,
        "championPointsUntilNextLevel": 5709,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 10,
        "lastPlayTime": 1567131244000
    },
    {
        "championLevel": 3,
        "chestGranted": false,
        "championPoints": 6690,
        "championPointsSinceLastLevel": 690,
        "championPointsUntilNextLevel": 5910,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 113,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 3,
        "chestGranted": false,
        "championPoints": 6205,
        "championPointsSinceLastLevel": 205,
        "championPointsUntilNextLevel": 6395,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 245,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 3,
        "chestGranted": false,
        "championPoints": 6156,
        "championPointsSinceLastLevel": 156,
        "championPointsUntilNextLevel": 6444,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 131,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 3,
        "chestGranted": false,
        "championPoints": 6144,
        "championPointsSinceLastLevel": 144,
        "championPointsUntilNextLevel": 6456,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 17,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 5874,
        "championPointsSinceLastLevel": 4074,
        "championPointsUntilNextLevel": 126,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 54,
        "lastPlayTime": 1563841095000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 5870,
        "championPointsSinceLastLevel": 4070,
        "championPointsUntilNextLevel": 130,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 98,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 5522,
        "championPointsSinceLastLevel": 3722,
        "championPointsUntilNextLevel": 478,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 89,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 5439,
        "championPointsSinceLastLevel": 3639,
        "championPointsUntilNextLevel": 561,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 105,
        "lastPlayTime": 1567129160000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 5426,
        "championPointsSinceLastLevel": 3626,
        "championPointsUntilNextLevel": 574,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 53,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 5387,
        "championPointsSinceLastLevel": 3587,
        "championPointsUntilNextLevel": 613,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 27,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 5373,
        "championPointsSinceLastLevel": 3573,
        "championPointsUntilNextLevel": 627,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 55,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 5252,
        "championPointsSinceLastLevel": 3452,
        "championPointsUntilNextLevel": 748,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 111,
        "lastPlayTime": 1567553117000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 5013,
        "championPointsSinceLastLevel": 3213,
        "championPointsUntilNextLevel": 987,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 2,
        "lastPlayTime": 1567127009000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 4643,
        "championPointsSinceLastLevel": 2843,
        "championPointsUntilNextLevel": 1357,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 75,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 4397,
        "championPointsSinceLastLevel": 2597,
        "championPointsUntilNextLevel": 1603,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 85,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 4208,
        "championPointsSinceLastLevel": 2408,
        "championPointsUntilNextLevel": 1792,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 59,
        "lastPlayTime": 1567554958000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 4175,
        "championPointsSinceLastLevel": 2375,
        "championPointsUntilNextLevel": 1825,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 80,
        "lastPlayTime": 1567568649000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 4120,
        "championPointsSinceLastLevel": 2320,
        "championPointsUntilNextLevel": 1880,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 121,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 3940,
        "championPointsSinceLastLevel": 2140,
        "championPointsUntilNextLevel": 2060,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 22,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 3854,
        "championPointsSinceLastLevel": 2054,
        "championPointsUntilNextLevel": 2146,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 5,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 3838,
        "championPointsSinceLastLevel": 2038,
        "championPointsUntilNextLevel": 2162,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 104,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 3784,
        "championPointsSinceLastLevel": 1984,
        "championPointsUntilNextLevel": 2216,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 4,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 3750,
        "championPointsSinceLastLevel": 1950,
        "championPointsUntilNextLevel": 2250,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 120,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 3625,
        "championPointsSinceLastLevel": 1825,
        "championPointsUntilNextLevel": 2375,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 91,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 3624,
        "championPointsSinceLastLevel": 1824,
        "championPointsUntilNextLevel": 2376,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 19,
        "lastPlayTime": 1564631637000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 3578,
        "championPointsSinceLastLevel": 1778,
        "championPointsUntilNextLevel": 2422,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 86,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 3516,
        "championPointsSinceLastLevel": 1716,
        "championPointsUntilNextLevel": 2484,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 14,
        "lastPlayTime": 1567313744000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 3497,
        "championPointsSinceLastLevel": 1697,
        "championPointsUntilNextLevel": 2503,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 115,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 3446,
        "championPointsSinceLastLevel": 1646,
        "championPointsUntilNextLevel": 2554,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 79,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": true,
        "championPoints": 3425,
        "championPointsSinceLastLevel": 1625,
        "championPointsUntilNextLevel": 2575,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 9,
        "lastPlayTime": 1567315977000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 3391,
        "championPointsSinceLastLevel": 1591,
        "championPointsUntilNextLevel": 2609,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 103,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 3321,
        "championPointsSinceLastLevel": 1521,
        "championPointsUntilNextLevel": 2679,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 127,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 3317,
        "championPointsSinceLastLevel": 1517,
        "championPointsUntilNextLevel": 2683,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 8,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 3294,
        "championPointsSinceLastLevel": 1494,
        "championPointsUntilNextLevel": 2706,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 50,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 2949,
        "championPointsSinceLastLevel": 1149,
        "championPointsUntilNextLevel": 3051,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 42,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 2873,
        "championPointsSinceLastLevel": 1073,
        "championPointsUntilNextLevel": 3127,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 101,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 2791,
        "championPointsSinceLastLevel": 991,
        "championPointsUntilNextLevel": 3209,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 30,
        "lastPlayTime": 1567816942000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 2754,
        "championPointsSinceLastLevel": 954,
        "championPointsUntilNextLevel": 3246,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 64,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 2740,
        "championPointsSinceLastLevel": 940,
        "championPointsUntilNextLevel": 3260,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 38,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 2730,
        "championPointsSinceLastLevel": 930,
        "championPointsUntilNextLevel": 3270,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 3,
        "lastPlayTime": 1567567687000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 2670,
        "championPointsSinceLastLevel": 870,
        "championPointsUntilNextLevel": 3330,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 29,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 2518,
        "championPointsSinceLastLevel": 718,
        "championPointsUntilNextLevel": 3482,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 34,
        "lastPlayTime": 1567278400000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 2495,
        "championPointsSinceLastLevel": 695,
        "championPointsUntilNextLevel": 3505,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 223,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 2411,
        "championPointsSinceLastLevel": 611,
        "championPointsUntilNextLevel": 3589,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 68,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 2405,
        "championPointsSinceLastLevel": 605,
        "championPointsUntilNextLevel": 3595,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 61,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 2405,
        "championPointsSinceLastLevel": 605,
        "championPointsUntilNextLevel": 3595,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 136,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 2395,
        "championPointsSinceLastLevel": 595,
        "championPointsUntilNextLevel": 3605,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 412,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 2394,
        "championPointsSinceLastLevel": 594,
        "championPointsUntilNextLevel": 3606,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 222,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 2388,
        "championPointsSinceLastLevel": 588,
        "championPointsUntilNextLevel": 3612,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 28,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 2276,
        "championPointsSinceLastLevel": 476,
        "championPointsUntilNextLevel": 3724,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 268,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 2195,
        "championPointsSinceLastLevel": 395,
        "championPointsUntilNextLevel": 3805,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 62,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 2193,
        "championPointsSinceLastLevel": 393,
        "championPointsUntilNextLevel": 3807,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 90,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 2124,
        "championPointsSinceLastLevel": 324,
        "championPointsUntilNextLevel": 3876,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 82,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 2111,
        "championPointsSinceLastLevel": 311,
        "championPointsUntilNextLevel": 3889,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 6,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 2068,
        "championPointsSinceLastLevel": 268,
        "championPointsUntilNextLevel": 3932,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 78,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 1908,
        "championPointsSinceLastLevel": 108,
        "championPointsUntilNextLevel": 4092,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 254,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 2,
        "chestGranted": false,
        "championPoints": 1804,
        "championPointsSinceLastLevel": 4,
        "championPointsUntilNextLevel": 4196,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 24,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 1733,
        "championPointsSinceLastLevel": 1733,
        "championPointsUntilNextLevel": 67,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 76,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 1730,
        "championPointsSinceLastLevel": 1730,
        "championPointsUntilNextLevel": 70,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 497,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 1701,
        "championPointsSinceLastLevel": 1701,
        "championPointsUntilNextLevel": 99,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 126,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 1644,
        "championPointsSinceLastLevel": 1644,
        "championPointsUntilNextLevel": 156,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 69,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 1570,
        "championPointsSinceLastLevel": 1570,
        "championPointsUntilNextLevel": 230,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 23,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 1519,
        "championPointsSinceLastLevel": 1519,
        "championPointsUntilNextLevel": 281,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 238,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 1457,
        "championPointsSinceLastLevel": 1457,
        "championPointsUntilNextLevel": 343,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 48,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 1443,
        "championPointsSinceLastLevel": 1443,
        "championPointsUntilNextLevel": 357,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 74,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 1385,
        "championPointsSinceLastLevel": 1385,
        "championPointsUntilNextLevel": 415,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 119,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 1358,
        "championPointsSinceLastLevel": 1358,
        "championPointsUntilNextLevel": 442,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 106,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 1320,
        "championPointsSinceLastLevel": 1320,
        "championPointsUntilNextLevel": 480,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 421,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 1290,
        "championPointsSinceLastLevel": 1290,
        "championPointsUntilNextLevel": 510,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 429,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 1259,
        "championPointsSinceLastLevel": 1259,
        "championPointsUntilNextLevel": 541,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 122,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 1250,
        "championPointsSinceLastLevel": 1250,
        "championPointsUntilNextLevel": 550,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 63,
        "lastPlayTime": 1567467496000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 1232,
        "championPointsSinceLastLevel": 1232,
        "championPointsUntilNextLevel": 568,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 112,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 1230,
        "championPointsSinceLastLevel": 1230,
        "championPointsUntilNextLevel": 570,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 1,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 1200,
        "championPointsSinceLastLevel": 1200,
        "championPointsUntilNextLevel": 600,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 143,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 1133,
        "championPointsSinceLastLevel": 1133,
        "championPointsUntilNextLevel": 667,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 58,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 1092,
        "championPointsSinceLastLevel": 1092,
        "championPointsUntilNextLevel": 708,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 114,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 974,
        "championPointsSinceLastLevel": 974,
        "championPointsUntilNextLevel": 826,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 267,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 916,
        "championPointsSinceLastLevel": 916,
        "championPointsUntilNextLevel": 884,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 555,
        "lastPlayTime": 1567900758000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 910,
        "championPointsSinceLastLevel": 910,
        "championPointsUntilNextLevel": 890,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 44,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 900,
        "championPointsSinceLastLevel": 900,
        "championPointsUntilNextLevel": 900,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 92,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 877,
        "championPointsSinceLastLevel": 877,
        "championPointsUntilNextLevel": 923,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 420,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 863,
        "championPointsSinceLastLevel": 863,
        "championPointsUntilNextLevel": 937,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 35,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 811,
        "championPointsSinceLastLevel": 811,
        "championPointsUntilNextLevel": 989,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 67,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 774,
        "championPointsSinceLastLevel": 774,
        "championPointsUntilNextLevel": 1026,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 157,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 752,
        "championPointsSinceLastLevel": 752,
        "championPointsUntilNextLevel": 1048,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 117,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 742,
        "championPointsSinceLastLevel": 742,
        "championPointsUntilNextLevel": 1058,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 516,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 734,
        "championPointsSinceLastLevel": 734,
        "championPointsUntilNextLevel": 1066,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 134,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 729,
        "championPointsSinceLastLevel": 729,
        "championPointsUntilNextLevel": 1071,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 161,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 643,
        "championPointsSinceLastLevel": 643,
        "championPointsUntilNextLevel": 1157,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 84,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 542,
        "championPointsSinceLastLevel": 542,
        "championPointsUntilNextLevel": 1258,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 43,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 516,
        "championPointsSinceLastLevel": 516,
        "championPointsUntilNextLevel": 1284,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 13,
        "lastPlayTime": 1567551144000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 405,
        "championPointsSinceLastLevel": 405,
        "championPointsUntilNextLevel": 1395,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 202,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 281,
        "championPointsSinceLastLevel": 281,
        "championPointsUntilNextLevel": 1519,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 432,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 276,
        "championPointsSinceLastLevel": 276,
        "championPointsUntilNextLevel": 1524,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 77,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 251,
        "championPointsSinceLastLevel": 251,
        "championPointsUntilNextLevel": 1549,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 107,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 244,
        "championPointsSinceLastLevel": 244,
        "championPointsUntilNextLevel": 1556,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 141,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 220,
        "championPointsSinceLastLevel": 220,
        "championPointsUntilNextLevel": 1580,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 164,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 214,
        "championPointsSinceLastLevel": 214,
        "championPointsUntilNextLevel": 1586,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 427,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 168,
        "championPointsSinceLastLevel": 168,
        "championPointsUntilNextLevel": 1632,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 26,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 131,
        "championPointsSinceLastLevel": 131,
        "championPointsUntilNextLevel": 1669,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 163,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 128,
        "championPointsSinceLastLevel": 128,
        "championPointsUntilNextLevel": 1672,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 142,
        "lastPlayTime": 1567560402000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 119,
        "championPointsSinceLastLevel": 119,
        "championPointsUntilNextLevel": 1681,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 266,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 115,
        "championPointsSinceLastLevel": 115,
        "championPointsUntilNextLevel": 1685,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 39,
        "lastPlayTime": 1562631217000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 99,
        "championPointsSinceLastLevel": 99,
        "championPointsUntilNextLevel": 1701,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 236,
        "lastPlayTime": 1567284057000
    },
    {
        "championLevel": 1,
        "chestGranted": false,
        "championPoints": 74,
        "championPointsSinceLastLevel": 74,
        "championPointsUntilNextLevel": 1726,
        "summonerId": "test",
        "tokensEarned": 0,
        "championId": 145,
        "lastPlayTime": 1562631217000
    }
]`

func GetAllChampionMasteriesHandlerFunc() champion_mastery.GetAllChampionMasteriesHandlerFunc {
	return champion_mastery.GetAllChampionMasteriesHandlerFunc(func(params champion_mastery.GetAllChampionMasteriesParams, principal interface{}) middleware.Responder {
		if !strings.HasPrefix(params.EncryptedSummonerID, "test") {
			res := champion_mastery.NewGetAllChampionMasteriesBadRequest().WithPayload(&models.Error{Status: &models.Status{StatusCode: 400, Message: "Bad Request - Exception decrypting test"}})
			return res
		} else if params.EncryptedSummonerID != "test" {
			res := champion_mastery.NewGetAllChampionMasteriesNotFound().WithPayload(&models.Error{Status: &models.Status{StatusCode: 404, Message: "Data Not Found"}})
			return res
		}
		res := champion_mastery.NewGetAllChampionMasteriesOK()
		lcm := &models.ListChampionMastery{}
		json.Unmarshal([]byte(RawData), lcm)
		res.SetPayload(*lcm)
		return res
	})
}
