package utils

import (
	"crypto/tls"
	"net/http"

	lolclient "github.com/andresperezl/gol/lolapi/client"
	"github.com/andresperezl/gol/region"
	runtimeclient "github.com/go-openapi/runtime/client"
)

// GetInternalAPIClient returns the default LeagueOfLegends clients generated by
// swagger
func GetInternalAPIClient(region region.Region) *lolclient.LeagueOfLegends {
	tCfg := lolclient.DefaultTransportConfig()
	tCfg.Host = region.GetRegionalEndpoint()
	return lolclient.NewHTTPClientWithConfig(nil, tCfg)
}

// GetTestAPIClient returns a INSECURE client that will send request to the
// specified host. This should be only be used for test porpuses
func GetTestAPIClient(host string) *lolclient.LeagueOfLegends {
	tCfg := lolclient.DefaultTransportConfig()
	tCfg.Host = host
	client := lolclient.NewHTTPClientWithConfig(nil, tCfg)
	tlsConfig := &tls.Config{
		InsecureSkipVerify: true,
	}
	tlsTransport := &http.Transport{TLSClientConfig: tlsConfig}

	rclient := client.Transport.(*runtimeclient.Runtime)
	rclient.Transport = tlsTransport
	return client
}
