---
swagger: '2.0'
info:
  title: 'League of Legends API'
  version: 'v4'
  termsOfService: 'https://developer.riotgames.com/terms'
basePath: '/lol'
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  '/champion-mastery/v4/champion-masteries/by-summoner/{encryptedSummonerId}':
    get:
      tags:
      - championMastery
      summary: 'Get all champion mastery entries sorted by number of champion points descending'
      externalDocs:
        url: 'https://developer.riotgames.com/apis#champion-mastery-v4/GET_getAllChampionMasteries'
      operationId: getAllChampionMasteries
      parameters:
      - '$ref': '#/parameters/encryptedSummonerId'
      responses:
        200:
          description: 'OK'
          schema:
            '$ref': '#/definitions/ListChampionMastery'
        400:
          '$ref': '#/responses/BadRequest'
        401:
          '$ref': '#/responses/Unauthorized'
        403:
          '$ref': '#/responses/Forbidden'
        404:
          '$ref': '#/responses/NotFound'
        405:
          '$ref': '#/responses/MethodNotAllowed'
        415:
          '$ref': '#/responses/UnsopportedMediaType'
        429:
          '$ref': '#/responses/RateLimitExceeded'
        500:
          '$ref': '#/responses/IntenalServerError'
        502:
          '$ref': '#/responses/BadGateway'
        503:
          '$ref': '#/responses/ServiceUnavailable'
        504:
          '$ref': '#/responses/GatewayTimeout'
  '/champion-mastery/v4/champion-masteries/by-summoner/{encryptedSummonerId}/by-champion/{championId}':
    get:
      tags:
      - championMastery
      summary: 'Get a champion mastery by player ID and champion ID'
      externalDocs:
        url: 'https://developer.riotgames.com/apis#champion-mastery-v4/GET_getChampionMastery'
      operationId: getChampionMastery
      parameters:
      - '$ref': '#/parameters/encryptedSummonerId'
      - '$ref': '#/parameters/championId'
      responses:
        200:
          description: 'OK'
          schema:
            '$ref': '#/definitions/ChampionMastery'
        400:
          '$ref': '#/responses/BadRequest'
        401:
          '$ref': '#/responses/Unauthorized'
        403:
          '$ref': '#/responses/Forbidden'
        404:
          '$ref': '#/responses/NotFound'
        405:
          '$ref': '#/responses/MethodNotAllowed'
        415:
          '$ref': '#/responses/UnsopportedMediaType'
        429:
          '$ref': '#/responses/RateLimitExceeded'
        500:
          '$ref': '#/responses/IntenalServerError'
        502:
          '$ref': '#/responses/BadGateway'
        503:
          '$ref': '#/responses/ServiceUnavailable'
        504:
          '$ref': '#/responses/GatewayTimeout'
  '/champion-mastery/v4/scores/by-summoner/{encryptedSummonerId}':
    get:
      tags:
      - championMastery
      summary: 'Get a champion mastery by player ID and champion ID'
      externalDocs:
        url: 'https://developer.riotgames.com/apis#champion-mastery-v4/GET_getChampionMasteryScore'
      operationId: getChampionMasteryScore
      parameters:
      - '$ref': '#/parameters/encryptedSummonerId'
      responses:
        200:
          description: 'OK'
          schema:
            type: integer
            format: int32
        400:
          '$ref': '#/responses/BadRequest'
        401:
          '$ref': '#/responses/Unauthorized'
        403:
          '$ref': '#/responses/Forbidden'
        404:
          '$ref': '#/responses/NotFound'
        405:
          '$ref': '#/responses/MethodNotAllowed'
        415:
          '$ref': '#/responses/UnsopportedMediaType'
        429:
          '$ref': '#/responses/RateLimitExceeded'
        500:
          '$ref': '#/responses/IntenalServerError'
        502:
          '$ref': '#/responses/BadGateway'
        503:
          '$ref': '#/responses/ServiceUnavailable'
        504:
          '$ref': '#/responses/GatewayTimeout'
  '/platform/v3/champion-rotations':
    get:
      tags:
      - champion
      summary: 'Returns champion rotations, including free-to-play and low-level free-to-play rotations'
      externalDocs:
        url: 'https://developer.riotgames.com/apis#champion-v3/GET_getChampionInfo'
      operationId: getChampionInfo
      responses:
        200:
          description: 'OK'
          schema:
            '$ref': '#/definitions/ChampionInfo'
        400:
          '$ref': '#/responses/BadRequest'
        401:
          '$ref': '#/responses/Unauthorized'
        403:
          '$ref': '#/responses/Forbidden'
        404:
          '$ref': '#/responses/NotFound'
        405:
          '$ref': '#/responses/MethodNotAllowed'
        415:
          '$ref': '#/responses/UnsopportedMediaType'
        429:
          '$ref': '#/responses/RateLimitExceeded'
        500:
          '$ref': '#/responses/IntenalServerError'
        502:
          '$ref': '#/responses/BadGateway'
        503:
          '$ref': '#/responses/ServiceUnavailable'
        504:
          '$ref': '#/responses/GatewayTimeout'
definitions:
  APIError:
    type: object
    readOnly: true
    properties:
      status:
        '$ref': '#/definitions/Status'
  Status:
    type: object
    readOnly: true
    properties:
      message:
        type: string
        readOnly: true
      status_code:
        type: integer
        readOnly: true
        format: int32
  ListChampionMastery:
    type: array
    readOnly: true
    items:
      '$ref': '#/definitions/ChampionMastery'
  ChampionMastery:
    type: object
    readOnly: true
    description: ' Contains single Champion Mastery information for player and champion combination'
    properties:
      chestGranted:
        '$ref': '#/definitions/ChestGranted'
      championLevel:
        '$ref': '#/definitions/ChampionLevel'
      championPoints:
        '$ref': '#/definitions/ChampionPoints'
      championId:
        '$ref': '#/definitions/ChampionId'
      championPointsUntilNextLevel:
        '$ref': '#/definitions/ChampionPointsUntilNextLevel'
      lastPlayTime:
        '$ref': '#/definitions/LastPlayTime'
      tokensEarned:
        '$ref': '#/definitions/TokensEarned'
      championPointsSinceLastLevel:
        '$ref': '#/definitions/ChampionPointsSinceLastLevel'
      summonerId:
        '$ref': '#/definitions/EncryptedSummonerId'
  ChestGranted:
    type: boolean
    readOnly: true
    description: 'Is chest granted for this champion or not in current season'
  ChampionLevel:
    type: integer
    readOnly: true
    format: int32
    description: 'Champion level for specified player and champion combination'
  ChampionPoints:
    type: integer
    readOnly: true
    format: int32
    description: 'Total number of champion points for this player and champion combination - they are used to determine championLevel'
  ChampionId:
    type: integer
    readOnly: true
    format: int64
    description: 'Champion ID'
  ChampionPointsUntilNextLevel:
    type: integer
    readOnly: true
    format: int64
    description: 'Number of points needed to achieve next level. Zero if player reached maximum champion level for this champion'
  LastPlayTime:
    type: integer
    readOnly: true
    format: int64
    description: 'Last time this champion was played by this player - in Unix milliseconds time format'
  TokensEarned:
    type: integer
    readOnly: true
    format: int32
    description: 'The token earned for this champion to levelup'
  ChampionPointsSinceLastLevel:
    type: integer
    readOnly: true
    format: int64
    description: 'Number of points earned since current level has been achieved'
  EncryptedSummonerId:
    type: string
    readOnly: true
    description: 'Summoner ID (Encrypted)'
  ChampionInfo:
    type: object
    properties:
      freeChampionIdsForNewPlayers:
        type: array
        items:
          type: integer
          format: int32
      freeChampionIds:
        type: array
        items:
          type: integer
          format: int32
      maxNewPlayerLevel:
        type: integer
        format: int32
parameters:
  encryptedSummonerId:
    name: encryptedSummonerId
    in: path
    type: string
    description: 'Summoner ID associated with the player'
    required: true
  championId:
    name: championId
    in: path
    type: integer
    format: int64
    description: 'Champion ID'
    required: true
responses:
  BadRequest:
    description: 'Bad request'
    schema:
      '$ref': '#/definitions/APIError'
  Unauthorized:
    description: 'Unauthorized'
    schema:
      '$ref': '#/definitions/APIError'
  Forbidden:
    description: 'Forbidden'
    schema:
      '$ref': '#/definitions/APIError'
  NotFound:
    description: 'Not found'
    schema:
      '$ref': '#/definitions/APIError'
  MethodNotAllowed:
    description: 'Method not allowed'
    schema:
      '$ref': '#/definitions/APIError'
  UnsopportedMediaType:
    description: 'Unsopported media type'
    schema:
      '$ref': '#/definitions/APIError'
  RateLimitExceeded:
    description: 'Rate limit Exceeded'
    schema:
      '$ref': '#/definitions/APIError'
  IntenalServerError:
    description: 'Internal server error'
    schema:
      '$ref': '#/definitions/APIError'
  BadGateway:
    description: 'Bad gateway'
    schema:
      '$ref': '#/definitions/APIError'
  ServiceUnavailable:
    description: 'Service Unavailable'
    schema:
      '$ref': '#/definitions/APIError'
  GatewayTimeout:
    description: 'Gateway timeout'
    schema:
      '$ref': '#/definitions/APIError'
securityDefinitions:
  APIKeyHeader:
    type: apiKey
    in: header
    name: X-Riot-Token
  APIKeyQueryParam:
    type: apiKey
    in: query
    name: api_key
security:
- APIKeyHeader: []
- APIKeyQueryParam: []
tags:
- name: championMastery
  externalDocs:
    url: 'https://developer.riotgames.com/apis#champion-mastery-v4'
- name: champion
  externalDocs:
    url: 'https://developer.riotgames.com/apis#champion-v3'
externalDocs:
  url: 'https://developer.riotgames.com/apis'
