// Code generated by go-swagger; DO NOT EDIT.

package league

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new league API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for league API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetLeagueEntriesExp gets all the league entries

At the request of a GitHub issue, we've added an experimental league-exp-v4 endpoint. This new endpoint is a duplicate of the endpoint in league-v4, but it also supports the apex tiers (Challenger, Grandmaster, and Master). In November we'll evaluate whether this endpoint delivers enough value to merit its continual support.
*/
func (a *Client) GetLeagueEntriesExp(params *GetLeagueEntriesExpParams, authInfo runtime.ClientAuthInfoWriter) (*GetLeagueEntriesExpOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetLeagueEntriesExpParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getLeagueEntriesExp",
		Method:             "GET",
		PathPattern:        "/lol/league-exp/v4/entries/{queue}/{tier}/{division}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetLeagueEntriesExpReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetLeagueEntriesExpOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getLeagueEntriesExp: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
