// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// ChampionID Champion ID
// swagger:model ChampionId
type ChampionID int64

// Validate validates this champion Id
func (m ChampionID) Validate(formats strfmt.Registry) error {
	return nil
}
