// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// TokenEarned The token earned for this champion to levelup
// swagger:model TokenEarned
type TokenEarned int32

// Validate validates this token earned
func (m TokenEarned) Validate(formats strfmt.Registry) error {
	return nil
}
