// Code generated by go-swagger; DO NOT EDIT.

package champion_mastery

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetChampionMasteryParams creates a new GetChampionMasteryParams object
// with the default values initialized.
func NewGetChampionMasteryParams() *GetChampionMasteryParams {
	var ()
	return &GetChampionMasteryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetChampionMasteryParamsWithTimeout creates a new GetChampionMasteryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetChampionMasteryParamsWithTimeout(timeout time.Duration) *GetChampionMasteryParams {
	var ()
	return &GetChampionMasteryParams{

		timeout: timeout,
	}
}

// NewGetChampionMasteryParamsWithContext creates a new GetChampionMasteryParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetChampionMasteryParamsWithContext(ctx context.Context) *GetChampionMasteryParams {
	var ()
	return &GetChampionMasteryParams{

		Context: ctx,
	}
}

// NewGetChampionMasteryParamsWithHTTPClient creates a new GetChampionMasteryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetChampionMasteryParamsWithHTTPClient(client *http.Client) *GetChampionMasteryParams {
	var ()
	return &GetChampionMasteryParams{
		HTTPClient: client,
	}
}

/*GetChampionMasteryParams contains all the parameters to send to the API endpoint
for the get champion mastery operation typically these are written to a http.Request
*/
type GetChampionMasteryParams struct {

	/*ChampionID
	  Champion ID

	*/
	ChampionID int64
	/*EncryptedSummonerID
	  Summoner ID associated with the player

	*/
	EncryptedSummonerID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get champion mastery params
func (o *GetChampionMasteryParams) WithTimeout(timeout time.Duration) *GetChampionMasteryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get champion mastery params
func (o *GetChampionMasteryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get champion mastery params
func (o *GetChampionMasteryParams) WithContext(ctx context.Context) *GetChampionMasteryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get champion mastery params
func (o *GetChampionMasteryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get champion mastery params
func (o *GetChampionMasteryParams) WithHTTPClient(client *http.Client) *GetChampionMasteryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get champion mastery params
func (o *GetChampionMasteryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithChampionID adds the championID to the get champion mastery params
func (o *GetChampionMasteryParams) WithChampionID(championID int64) *GetChampionMasteryParams {
	o.SetChampionID(championID)
	return o
}

// SetChampionID adds the championId to the get champion mastery params
func (o *GetChampionMasteryParams) SetChampionID(championID int64) {
	o.ChampionID = championID
}

// WithEncryptedSummonerID adds the encryptedSummonerID to the get champion mastery params
func (o *GetChampionMasteryParams) WithEncryptedSummonerID(encryptedSummonerID string) *GetChampionMasteryParams {
	o.SetEncryptedSummonerID(encryptedSummonerID)
	return o
}

// SetEncryptedSummonerID adds the encryptedSummonerId to the get champion mastery params
func (o *GetChampionMasteryParams) SetEncryptedSummonerID(encryptedSummonerID string) {
	o.EncryptedSummonerID = encryptedSummonerID
}

// WriteToRequest writes these params to a swagger request
func (o *GetChampionMasteryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param championId
	if err := r.SetPathParam("championId", swag.FormatInt64(o.ChampionID)); err != nil {
		return err
	}

	// path param encryptedSummonerId
	if err := r.SetPathParam("encryptedSummonerId", o.EncryptedSummonerID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
